name: Maven Test Pipeline

on:
  push:
    branches: [ master ]  

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Clear Maven Cache
        run: rm -rf ~/.m2/repository

      - name: Build and test with Maven
        run: |
          mvn clean test -e -X \
            -DargLine="--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED"

      - name: Upload Test Reports (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: target/surefire-reports/*.xml
